### ISSUE TITLE
Dependency to deprecated package System.IO.FileSystem.AccessControl

### ISSUE THREAD

**Issue by AnKiLa** [microsoft/ApplicationInsights-SnapshotCollector#23]
The NuGet package of ApplicationInsights-SnapshotCollector has got a dependency to 
System.IO.FileSystem.AccessControl (>=4.7.0).

System.IO.FileSystem.AccessControl is marked as deprecated. 

Is there any planned solution or workaround for this issue?

**Comment by pharring** [comment]
Thanks for the question, @AnKiLa. I know we don't reference the latest version, but I was unaware that the package is deprecated. How did you discover that it's deprecated? Do you think that upgrading to a newer version would work, or do we need to move to an alternative package altogether?

**Comment by AnKiLa** [comment]
Hello @pharring, my Visual Studio package manager marks it as deprecated.
![image](https://github.com/microsoft/ApplicationInsights-SnapshotCollector/assets/78601258/26f274d2-493d-4f66-9fd8-98145714d9a1)

You can find this information on following link too:
https://www.nuget.org/packages/System.IO.FileSystem.AccessControl/

Version 5.0.0. is also deprecatred, so I fear the only solution is to switch to an alternative package.

**Comment by pharring** [comment]
Thanks for bringing this to our attention, but we don't think we need to change anything.

According to nuget.org, only the 5.0.0 version is deprecated. As you noted, SnapshotCollector references version 4.7.0 which isn't deprecated. From the screenshot, your build references the 5.0.0 version, so that reference must be coming from some other component in your build.

For now, at least, we need to continue to support down-level .NET versions -- even some of those out of support, such as .NET 3.1. Additionally, SnapshotCollector supports both .NET Framework and .NET Core applications through a single netstandard2.0 target. The System.IO.FileSystem.AccessControl types aren't available in the netstandard2.0 surface area, which is why we need to bring them in with that extra NuGet.

**Comment by AnKiLa** [comment]
@pharring Thanks for clarification. You are right, due to an internal programming policy which states to always use latest available versions of NuGet packages I have updated System.IO.FileSystem.AccessControl to version 5.0.0. manually.

SnapshotCollector currently shows dependencies of at least v4.7.0 to System.IO.FileSystem.AccessControl. To avoid warnings, probably this dependency should be changed to <=4.7.0. then.
